table table
	lineageTag: 8d642878-1b3c-4d2d-9cd6-7d25f13b0fb3

	column Status
		dataType: string
		lineageTag: 74f348a6-a147-41d5-b454-9e1848a38a4e
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column Paraplanner
		dataType: string
		lineageTag: 26073ad1-89f4-4717-912e-3e18eaeb0325
		summarizeBy: none
		sourceColumn: Paraplanner

		annotation SummarizationSetBy = Automatic

	column Adviser
		dataType: string
		lineageTag: b2ccefe6-6c8e-4f4d-87f2-f912415f9c9e
		summarizeBy: none
		sourceColumn: Adviser

		annotation SummarizationSetBy = Automatic

	column CRM
		dataType: string
		lineageTag: 8c2f86a8-0278-4b5a-85e5-1efb40cc5f6d
		summarizeBy: none
		sourceColumn: CRM

		annotation SummarizationSetBy = Automatic

	column 'Advice Type'
		dataType: string
		lineageTag: a1cb9928-2c3f-4aa7-8183-4e7679f4003c
		summarizeBy: none
		sourceColumn: Advice Type

		annotation SummarizationSetBy = Automatic

	column 'Client Type'
		dataType: string
		lineageTag: cd7cf35a-7b58-427b-b929-1f0288f0ba19
		summarizeBy: none
		sourceColumn: Client Type

		annotation SummarizationSetBy = Automatic

	column Meeting
		dataType: dateTime
		formatString: General Date
		lineageTag: 61ced5d2-ac36-4566-b310-035eb20df178
		summarizeBy: none
		sourceColumn: Meeting

		variation Variation
			isDefault
			relationship: 4ccc9677-a018-4002-8bbf-c790aa3da946
			defaultHierarchy: LocalDateTable_23324602-591b-4146-b07b-e95bb84184b4.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Requested
		dataType: dateTime
		formatString: General Date
		lineageTag: cdcc6777-0deb-4e20-8680-892658896042
		summarizeBy: none
		sourceColumn: Requested

		variation Variation
			isDefault
			relationship: b5ad9e9b-0c29-4586-af7e-e82e44d7b184
			defaultHierarchy: LocalDateTable_1a74a9f3-3c0c-4bc4-a95e-d8fe4474eb5f.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Due Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: e0268adf-ee7b-4fa4-9ad0-48a23bf9b63a
		summarizeBy: none
		sourceColumn: Due Date

		variation Variation
			isDefault
			relationship: 6100ac03-3a17-4a35-ba9e-44ca9609edb9
			defaultHierarchy: LocalDateTable_92162e5f-a1ae-4378-8ea9-e56be33d97d8.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Date Completed'
		dataType: dateTime
		formatString: General Date
		lineageTag: 3c060ad6-a955-41ce-8321-4e314e04efda
		summarizeBy: none
		sourceColumn: Date Completed

		variation Variation
			isDefault
			relationship: c8e96d52-0601-4094-ba1f-a7355b05e3ad
			defaultHierarchy: LocalDateTable_c338d219-8c2b-4c23-9b51-23ec09d12ad3.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Advice Areas'
		dataType: string
		lineageTag: 0bc33bf8-8d9e-4a5e-9e0c-ddbe01850993
		summarizeBy: none
		sourceColumn: Advice Areas

		annotation SummarizationSetBy = Automatic

	column Notes
		dataType: string
		lineageTag: 9bb7c6ac-11c3-4636-a715-f1b5a097db73
		summarizeBy: none
		sourceColumn: Notes

		annotation SummarizationSetBy = Automatic

	column 'Completion Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: ff2881ff-63c7-44c6-b301-08031df097ad
		summarizeBy: none
		sourceColumn: Completion Date

		variation Variation
			isDefault
			relationship: 20247390-2f17-4ea3-a6cc-a619d9acf138
			defaultHierarchy: LocalDateTable_119e8e70-0a92-427a-9284-ebcc05533ff7.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Location
		dataType: string
		lineageTag: 00ababf4-af64-4bbb-baa4-a1e923501551
		summarizeBy: none
		sourceColumn: Location

		annotation SummarizationSetBy = Automatic

	column ID
		dataType: int64
		formatString: 0
		lineageTag: da023eb1-2431-49a9-95a6-54d6d77894b1
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	partition table = m
		mode: import
		source = ```
				let
				                    Source = SharePoint.Tables("https://dreamitcs2020-my.sharepoint.com/personal/anuj_dreamitcs_com", [Implementation= "2.0", ViewMode = "Default"]), 
				                    Navigation = Source{[Id="1242851a-8516-41c7-a5d5-2a537990dc95"]}[Items],
				                    TableSchema = Table.Schema(Navigation),
				                    UserMultiTypeRows = Table.SelectRows(TableSchema, each [NativeTypeName] = "UserMulti"),
				UserMultiFieldNames = {"id", "value", "title", "email", "sip", "picture", "jobTitle", "department"},
				UserMultiTransforms = Table.AddColumn(UserMultiTypeRows, "UserMultiTransform", each(name) => 
				                    if (name <> "") then @Text.Combine(Table.Column(Table.FromList(name, Record.FieldValues, UserMultiFieldNames), "title"), ", ") else null, Function.Type),
				UserMultiChanges = Table.ToRows(Table.SelectColumns(UserMultiTransforms, { "Name","UserMultiTransform"})),
				ExpandedUserMulti = Table.TransformColumns(Navigation, UserMultiChanges, null, MissingField.UseNull),
				                    UserTypeRows = Table.SelectRows(TableSchema, each [NativeTypeName] = "User"),
				UserFieldNames = {"id", "title", "email", "sip", "picture", "jobTitle", "department"},
				UserTransforms = Table.AddColumn(UserTypeRows, "UserTransform", each(name) => 
				                    if (name <> "") then @Text.Combine(Table.Column(Table.FromList(name, Record.FieldValues, UserFieldNames), "title"), ", ") else null, Function.Type),
				UserChanges = Table.ToRows(Table.SelectColumns(UserTransforms, { "Name","UserTransform"})),
				ExpandedUser = Table.TransformColumns(ExpandedUserMulti, UserChanges, null, MissingField.UseNull),
				                    LookupTypeRows = Table.SelectRows(TableSchema, each [NativeTypeName] = "Lookup"),
				LookupFieldNames = {"lookupId", "lookupValue", "isSecretFieldValue"},
				LookupTransforms = Table.AddColumn(LookupTypeRows, "LookupTransform", each(name) => 
				                    if (name <> "") then @Text.Combine(Table.Column(Table.FromList(name, Record.FieldValues, LookupFieldNames), "lookupValue"), ", ") else null, Function.Type),
				LookupChanges = Table.ToRows(Table.SelectColumns(LookupTransforms, { "Name","LookupTransform"})),
				ExpandedLookup = Table.TransformColumns(ExpandedUser, LookupChanges, null, MissingField.UseNull),
				                    TaxonomyFieldTypeTypeRows = Table.SelectRows(TableSchema, each [NativeTypeName] = "TaxonomyFieldType"),
				TaxonomyFieldTypeTransforms = Table.AddColumn(TaxonomyFieldTypeTypeRows, "TaxonomyFieldTypeTransform", each (name) => 
				                        if (name <> "") then @Text.Combine(Table.Column(Table.FromRecords({ name }), "Label")) else null, Function.Type),
				TaxonomyFieldTypeChanges = Table.ToRows(Table.SelectColumns(TaxonomyFieldTypeTransforms, { "Name","TaxonomyFieldTypeTransform"})),
				ExpandedTaxonomyFieldType = Table.TransformColumns(ExpandedLookup, TaxonomyFieldTypeChanges, null, MissingField.UseNull),
				                    LocationTypeRows = Table.SelectRows(TableSchema, each [NativeTypeName] = "Location"),
				LocationTransforms = Table.AddColumn(LocationTypeRows, "LocationTransform", each (name) => 
				                        if (name <> "") then @Text.Combine(Table.Column(Table.FromRecords({ name }), "DisplayName")) else null, Function.Type),
				LocationChanges = Table.ToRows(Table.SelectColumns(LocationTransforms, { "Name","LocationTransform"})),
				ExpandedLocation = Table.TransformColumns(ExpandedTaxonomyFieldType, LocationChanges, null, MissingField.UseNull),
				                    ThumbnailTypeRows = Table.SelectRows(TableSchema, each [NativeTypeName] = "Thumbnail"),
				ThumbnailTransforms = Table.AddColumn(ThumbnailTypeRows, "ThumbnailTransform", each (name) => 
				                        if (name <> "") then @Text.Combine(Table.Column(Table.FromRecords({ name }), "fileName")) else null, Function.Type),
				ThumbnailChanges = Table.ToRows(Table.SelectColumns(ThumbnailTransforms, { "Name","ThumbnailTransform"})),
				ExpandedThumbnail = Table.TransformColumns(ExpandedLocation, ThumbnailChanges, null, MissingField.UseNull),
				                    LookupMultiTypeRows = Table.SelectRows(TableSchema, each [NativeTypeName] = "LookupMulti"),
				LookupMultiFieldNames = {"lookupId", "lookupValue", "isSecretFieldValue"},
				LookupMultiTransforms = Table.AddColumn(LookupMultiTypeRows, "LookupMultiTransform", each(name) => 
				                    if (name <> "") then @Text.Combine(Table.Column(Table.FromList(name, Record.FieldValues, LookupMultiFieldNames), "lookupValue"), ", ") else null, Function.Type),
				LookupMultiChanges = Table.ToRows(Table.SelectColumns(LookupMultiTransforms, { "Name","LookupMultiTransform"})),
				ExpandedLookupMulti = Table.TransformColumns(ExpandedThumbnail, LookupMultiChanges, null, MissingField.UseNull),
				                    TaxonomyFieldTypeMultiTypeRows = Table.SelectRows(TableSchema, each [NativeTypeName] = "TaxonomyFieldTypeMulti"),
				TaxonomyFieldTypeMultiFieldNames = {"Label", "TermID"},
				TaxonomyFieldTypeMultiTransforms = Table.AddColumn(TaxonomyFieldTypeMultiTypeRows, "TaxonomyFieldTypeMultiTransform", each(name) => 
				                    if (name <> "") then @Text.Combine(Table.Column(Table.FromList(name, Record.FieldValues, TaxonomyFieldTypeMultiFieldNames), "Label"), ", ") else null, Function.Type),
				TaxonomyFieldTypeMultiChanges = Table.ToRows(Table.SelectColumns(TaxonomyFieldTypeMultiTransforms, { "Name","TaxonomyFieldTypeMultiTransform"})),
				ExpandedTaxonomyFieldTypeMulti = Table.TransformColumns(ExpandedLookupMulti, TaxonomyFieldTypeMultiChanges, null, MissingField.UseNull),
				                    MultiChoiceTypeRows = Table.SelectRows(TableSchema, each [NativeTypeName] = "MultiChoice"),
				MultiChoiceTransforms = Table.AddColumn(MultiChoiceTypeRows, "MultiChoiceTransform", each(name) => 
				                    if (name <> "") then @Text.Combine(name, ", ") else null, Function.Type),
				MultiChoiceChanges = Table.ToRows(Table.SelectColumns(MultiChoiceTransforms, { "Name","MultiChoiceTransform"})),
				ExpandedMultiChoice = Table.TransformColumns(ExpandedTaxonomyFieldTypeMulti, MultiChoiceChanges, null, MissingField.UseNull)
				                in ExpandedMultiChoice
				```

	annotation PBI_ResultType = Table

