table Competition
	lineageTag: 62ca06c3-3f85-4cf4-ba58-6beb201ce0f9

	column 'Store Nbr'
		dataType: int64
		formatString: 0
		lineageTag: 7c76b8ae-4fc8-4134-903a-89b0f550d4c8
		summarizeBy: none
		sourceColumn: Store Nbr

		annotation SummarizationSetBy = Automatic

	column Competitor
		dataType: string
		lineageTag: 5958fef5-d942-4ef2-81f0-d0a382a0b5a8
		summarizeBy: none
		sourceColumn: Competitor

		annotation SummarizationSetBy = Automatic

	partition Competition-d6f82880-37f4-4042-bb18-4efc364e9a05 = m
		mode: import
		queryGroup: Dimensions
		source =
				let
				    Source = Sql.Database("45abcdnsw5ru7e2ughqdsi5nlu-ttswb43k6wtebajhba5hzpoqhu.datawarehouse.fabric.microsoft.com", "GoldLakehouse", [Query="select [$Table].[Store_Nbr] as [Store Nbr],#(lf)    [$Table].[Competitor] as [Competitor]#(lf)from [dbo].[StoreCompetitionCanada] as [$Table]"]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Store Nbr", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

