table CustomSortByMeasure
	lineageTag: ca801c74-6985-4515-ac76-7717cd086cf1

	column Sort
		dataType: string
		lineageTag: f47b156a-65f4-4d1d-b0ce-09bf7ce87901
		summarizeBy: none
		sourceColumn: Sort

		annotation SummarizationSetBy = Automatic

	column Order
		dataType: int64
		formatString: 0
		lineageTag: 6e554719-8fbf-4ed6-b18b-bd1a05bc7224
		summarizeBy: sum
		sourceColumn: Order

		annotation SummarizationSetBy = Automatic

	column Metrics
		dataType: string
		lineageTag: c4d8d861-831d-42ec-ab90-48f96bcf7fb2
		summarizeBy: none
		sourceColumn: Metrics
		sortByColumn: Order

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition CustomSortByMeasure-4b1ff184-1088-416f-a379-551e86db631f = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WCs4vKlFwqlQIiVRQiSk1MDAyL1bSUTIEYmSRWB2ESh8UlUZA7INDJcgEBeeMdKASYyCGsDEUqEKVmICVqGJTFPqoYSbIMlOIsyBcNDfB1JhBHISpBqQRapU5EIditQjuGguwEkzXOAYFABUCJS2BGMpBl/cByRsaQBX4YCqAWGFoCFWBzQ6YOwyNoIowneKZF1ySn5ytoApUAbIMwY+NBQA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t, Order = _t, Attribute = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}, {"Order", Int64.Type}, {"Attribute", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Attribute", "Metrics"}, {"Column1", "Sort"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

