table 'Segment table'
	lineageTag: 56277d14-dd85-43c8-afa6-139771a98b9f

	column group
		dataType: string
		lineageTag: 6bfa5dfc-6a7c-4531-a6bf-dcc4aed5f3a2
		summarizeBy: none
		sourceColumn: group

		annotation SummarizationSetBy = Automatic

	column 'sub group'
		dataType: string
		lineageTag: 65cbe676-b81f-46e8-bc87-536c8f2d8f5e
		summarizeBy: none
		sourceColumn: sub group

		annotation SummarizationSetBy = Automatic

	column 'group order'
		dataType: int64
		formatString: 0
		lineageTag: 90099b8e-a7f2-42e2-9281-9a221ea082df
		summarizeBy: sum
		sourceColumn: group order

		annotation SummarizationSetBy = Automatic

	column 'Sub group order'
		dataType: int64
		formatString: 0
		lineageTag: fe436f74-c626-4180-a8c9-b0a003571059
		summarizeBy: sum
		sourceColumn: Sub group order

		annotation SummarizationSetBy = Automatic

	partition 'Segment table' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WcsvMS80BYgWX1OJkJR0MviEYx+pgqgxLzUvJL4IqMcKqxKkoMS8F2SRjrMo8S1Jzi6EqTMAq4GbDGUZAbIoqh2I6SN4MVR5mLEjKHCyFogOFYwzEFphqYEaApC3B0jARGG0CcreBUmwsAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [group = _t, #"sub group" = _t, #"group order" = _t, #"Sub group order" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"group", type text}, {"sub group", type text}, {"group order", Int64.Type}, {"Sub group order", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

