name: Merge Clone to Test

on:
  push:
    branches:
      - cloneprojectbranch

jobs:
  merge-clone-to-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout test branch
        uses: actions/checkout@v3
        with:
          ref: test

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Merge cloneprojectbranch into test
        run: |
          git fetch origin cloneprojectbranch
          git merge origin/cloneprojectbranch --no-edit
          git push origin test


      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
